### ISSUE TITLE
ValueError in LambdifyCSE

### ISSUE THREAD

**Issue by bjodah** [symengine/symengine.py#105]
just to write this down (will look into it when time allows)

Using python3.5 ppa:symengine on Ubuntu 16.04:
```
>>> import symengine
>>> x, y, z = symengine.symbols('x y z')
>>> expr1, expr2 = x+y+z, x*y*z
>>> callback = symengine.LambdifyCSE([x, y, z], [expr1, expr2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "symengine/lib/symengine_wrapper.pyx", line 2846, in symengine.lib.symengine_wrapper.LambdifyCSE (/build/python-symengine-Hx0GFi/python-symengine-0.2.0-ubuntu2/build/lib.linux-x86_64-3.5/symengine/lib/symengine_wrapper.cpp:70862)
ValueError: need more than 0 values to unpack
>>> callback = symengine.Lambdify([x, y, z], [expr1, expr2])
>>> callback([2, 3, 4])
array([  9.,  24.])
```

**Comment by certik** [comment]
Thanks for reporting it. Which SymPy version are you using?

**Comment by sighingnow** [comment]
I can reproduce this bug with sympy 1.0. This bug may comes from the difference of symbol's representation between symengine and sympy. A more representative case is as follows:

~~~python
In [1]: import sympy
In [2]: import symengine

In [3]: x, y, z = sympy.symbols('x y z')
In [4]: expr1, expr2 = x+y+z+z*y, x*y*z+z*y

In [5]: sympy.cse([expr1, expr2])
Out[5]: ([(x0, y*z)], [x + x0 + y + z, x*x0 + x0])

In [6]: x, y, z = symengine.symbols('x y z')
In [7]: expr1, expr2 = x+y+z+z*y, x*y*z+z*y

In [8]: sympy.cse([expr1, expr2])
Out[8]: ([], [x + y + z + y*z, y*z + x*y*z])
~~~

**Comment by bjodah** [comment]
@sighingnow yes that seems to be the source of the bug. @certik I used SymPy 1.0

Here is a short docker based test for reproducibility (admittedly a bit overkill):
```
$ cat <<EOF | docker run --rm -i ubuntu:xenial bash -x
echo "deb http://ppa.launchpad.net/symengine/ppa/ubuntu xenial main" >>/etc/apt/sources.list
apt-get update
apt-get install --assume-yes --allow-unauthenticated --no-install-recommends python-symengine
python -c "import symengine as s; x, y, z = s.symbols('x y z'); e1, e2 = x+y+z+z*y, x*y*z+z*y; import sympy; print(sympy.cse([e1, e2]))"
EOF
...
([], [x + y + z + y*z, y*z + x*y*z])
```

**Comment by isuruf** [comment]
These are two problems actually. @bjodah's issue is that LambdifyCSE doesn't handle the case where subs is empty (as it should be because there are no common subexpressions in the two original expressions except for the symbols). SymPy's cse giving empty subs is another issue.
