### ISSUE TITLE
lambdifying a function with imaginary unit returns Error

### ISSUE THREAD

**Issue by BlackTeaAndCoffee** [symengine/symengine.py#138]
Hi, 

i stumbled on a problem. If you take the Lamdify.py code from your benchmarks and add the imaginary unit to the code. It shows the following Error. 
```
Traceback (most recent call last):
  File "foo.py", line 16, in <module>
    lmb_symengine = se.Lambdify(args, exprs)
  File "symengine/lib/symengine_wrapper.pyx", line 2646, in symengine.lib.symengine_wrapper.Lambdify.__cinit__ (/build/python-symengine-DwGdyH/python-symengine-0.2.0-ubuntu2/build/lib.linux-i686-3.5/symengine/lib/symengine_wrapper.cpp:66640)
RuntimeError: Not Implemented
```
The code is the following. If i delete the imaginary Unit I, everything is fine.

```
from time import clock
from sympy import I
import numpy as np
import sympy as sp
import symengine as se



x = sp.symarray('x', 14)
p = sp.symarray('p', 14)
args = np.concatenate((x, p))
exp = sp.exp

#X[1] gets the imaginary number
exprs = [sp.cos(x[0]) + I*x[1] - x[4] + 36.252574322669, x[0] - x[2] + x[3] +
        exp(x[13]) + exp(x[5]) + exp(x[6]) + exp(x[7]) + exp(x[8]) + exp(x[9])]

print(exprs)
lmb_symengine = se.Lambdify(args, exprs)
lmb_sympy = sp.lambdify(args, exprs)
```

**Comment by isuruf** [comment]
API is a little different than SymPy. Use `se.Lambdify(args, exprs, real=False)` for complex arguments.

**Comment by BlackTeaAndCoffee** [comment]
it works, 

thanks!
