### ISSUE TITLE
ModuleNotFoundError: No module named 'symengine.lib.symengine_wrapper'

### ISSUE THREAD

**Issue by astahlhofen** [symengine/symengine.py#186]
Hi,

I installed symengine and the symengine-python-wrapper from source. The build was successful and everything exit without errors. But if I write
```
import symengine
```
I get the following ERROR:
```
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import symengine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/Data/andi/Applications/symengine-python/symengine/__init__.py", line 1, in <module>
    from .lib.symengine_wrapper import (Symbol, S, sympify,
ModuleNotFoundError: No module named 'symengine.lib.symengine_wrapper'
```

Do you have any suggestion why this error occurs?

Thanks in advance!

P.S.: I'm using v0.3.0 of symengine and the python wrapper. The output of the symengine-python-wrapper build looks as followed:

```
[andi@dhcp227 ~/Applications/symengine-python]$ git st
HEAD detached at v0.3.0
nothing to commit, working tree clean
[andi@dhcp227 ~/Applications/symengine-python]$ python3 setup.py install --record files.txt
running install
running build
running build_ext
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
SymEngine_DIR : /usr/local/lib/cmake/symengine
-- Python include path: /Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m
-- Python version: 3.6
-- Python install path: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
-- Found PYTHON: /Library/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6.dylib  
-- Found CYTHON: cython
CMAKE_BUILD_TYPE        : Release
CMAKE_CXX_FLAGS_RELEASE : -std=c++11 -Wall -Wextra -fPIC -O3 -ffast-math -funroll-loops -Wno-unused-parameter -march=native -D__extern_always_inline=inline -Wno-unknown-pragmas
CMAKE_CXX_FLAGS_DEBUG   : -std=c++11 -Wall -Wextra -fPIC -g -Wno-unused-parameter -ggdb -Wno-unknown-pragmas
HAVE_SYMENGINE_MPFR     : True
HAVE_SYMENGINE_MPC      : False
HAVE_SYMENGINE_PIRANHA  : False
HAVE_SYMENGINE_FLINT    : False
HAVE_SYMENGINE_LLVM     : False
Copying source of python wrappers into: /Volumes/Data/andi/Applications/symengine-python/build/lib.macosx-10.6-intel-3.6
-- Configuring done
-- Generating done
-- Build files have been written to: /Volumes/Data/andi/Applications/symengine-python/build/lib.macosx-10.6-intel-3.6
[ 25%] Cythonizing symengine_wrapper.pyx
Scanning dependencies of target symengine_wrapper
[ 50%] Building CXX object symengine/lib/CMakeFiles/symengine_wrapper.dir/symengine_wrapper.cpp.o
/Volumes/Data/andi/Applications/symengine-python/build/lib.macosx-10.6-intel-3.6/symengine/lib/symengine_wrapper.cpp:94321:37: warning: 
      comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int'
      [-Wsign-compare]
    for (__pyx_t_15 = 0; __pyx_t_15 < __pyx_t_8; __pyx_t_15+=1) {
                         ~~~~~~~~~~ ^ ~~~~~~~~~
1 warning generated.
[ 75%] Building CXX object symengine/lib/CMakeFiles/symengine_wrapper.dir/pywrapper.cpp.o
[100%] Linking CXX shared module symengine_wrapper.cpython-36m-darwin.so
[100%] Built target symengine_wrapper
running install_egg_info
running egg_info
creating symengine.egg-info
writing symengine.egg-info/PKG-INFO
writing dependency_links to symengine.egg-info/dependency_links.txt
writing top-level names to symengine.egg-info/top_level.txt
writing manifest file 'symengine.egg-info/SOURCES.txt'
reading manifest file 'symengine.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.hpp' under directory 'symengine'
warning: no files found matching '*.cmake' under directory 'symengine'
warning: no files found matching '*.pxi' under directory 'symengine'
warning: no files found matching '*.in' under directory 'cmake'
writing manifest file 'symengine.egg-info/SOURCES.txt'
removing '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine-0.3.0-py3.6.egg-info' (and everything under it)
Copying symengine.egg-info to /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine-0.3.0-py3.6.egg-info
running install_scripts
writing list of installed files to 'files.txt'
SymEngine_DIR : /usr/local/lib/cmake/symengine
-- Python include path: /Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m
-- Python version: 3.6
-- Python install path: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
-- Found CYTHON: cython
CMAKE_BUILD_TYPE        : Release
CMAKE_CXX_FLAGS_RELEASE : -std=c++11 -Wall -Wextra -fPIC -O3 -ffast-math -funroll-loops -Wno-unused-parameter -march=native -D__extern_always_inline=inline -Wno-unknown-pragmas
CMAKE_CXX_FLAGS_DEBUG   : -std=c++11 -Wall -Wextra -fPIC -g -Wno-unused-parameter -ggdb -Wno-unknown-pragmas
HAVE_SYMENGINE_MPFR     : True
HAVE_SYMENGINE_MPC      : False
HAVE_SYMENGINE_PIRANHA  : False
HAVE_SYMENGINE_FLINT    : False
HAVE_SYMENGINE_LLVM     : False
Copying source of python wrappers into: /Volumes/Data/andi/Applications/symengine-python/build/lib.macosx-10.6-intel-3.6
-- Configuring done
-- Generating done
-- Build files have been written to: /Volumes/Data/andi/Applications/symengine-python/build/lib.macosx-10.6-intel-3.6
[100%] Built target symengine_wrapper
Install the project...
-- Install configuration: "Release"
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/__init__.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/utilities.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/compatibility.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/sympy_compat.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/functions.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/printing.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/lib/symengine_wrapper.cpython-36m-darwin.so
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/lib/__init__.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/lib/config.pxi
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/lib/symengine.pxd
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/lib/symengine_wrapper.pxd
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/lib/pywrapper.h
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/__init__.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_arit.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_dict_basic.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_eval.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_expr.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_functions.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_number.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_matrices.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_ntheory.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_printing.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_sage.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_series_expansion.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_subs.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_symbol.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_sympify.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_sympy_conv.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_var.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_lambdify.py
-- Installing: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_sympy_compat.py
Listing '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/__init__.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/compatibility.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/functions.py'...
Listing '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/lib'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/lib/__init__.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/printing.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/sympy_compat.py'...
Listing '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/__init__.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_arit.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_dict_basic.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_eval.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_expr.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_functions.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_lambdify.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_matrices.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_ntheory.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_number.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_printing.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_sage.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_series_expansion.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_subs.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_symbol.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_sympify.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_sympy_compat.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_sympy_conv.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/tests/test_var.py'...
Compiling '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/symengine/utilities.py'...
```

**Comment by astahlhofen** [comment]
I solved the issue :-) I think it didn't uninstall an old version symengine correctly. After cleaning everything up and double check that git-tag versions of symengine and symengine.py matches, everything works fine.
Thank you for this greate stuff :-)
