### ISSUE TITLE
symengine.py does not correctly link to libpython

### ISSUE THREAD

**Issue by woodscn** [symengine/symengine.py#23]
Placing a symlink to libpython in the cwd works around the problem.

```
~$ python -c "import symengine"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/anaconda3/lib/python3.4/site-packages/symengine/__init__.py", line 1, in <module>
    from .lib.symengine_wrapper import (Symbol, Integer, sympify, SympifyError,
ImportError: dlopen(~/anaconda3/lib/python3.4/site-packages/symengine/lib/symengine_wrapper.cpython-34m.so, 2): Library not loaded: libpython3.4m.dylib
  Referenced from: ~/anaconda3/lib/python3.4/site-packages/symengine/lib/symengine_wrapper.cpython-34m.so
  Reason: image not found
```

Per comments here: http://stackoverflow.com/questions/26815537/opencv-3-0-0-alpha-with-python-3-failed-to-import-cv2

```
~$ otool -L ~/anaconda3/lib/python3.4/site-packages/symengine/lib/symengine_wrapper.cpython-34m.so 
~/anaconda3/lib/python3.4/site-packages/symengine/lib/symengine_wrapper.cpython-34m.so:
	libpython3.4m.dylib (compatibility version 3.4.0, current version 3.4.0)
	~/opt/gmp/lib/libgmpxx.4.dylib (compatibility version 9.0.0, current version 9.0.0)
	~/opt/gmp/lib/libgmp.10.dylib (compatibility version 13.0.0, current version 13.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

**Comment by isuruf** [comment]
Thanks for the bug report. Can you try the following patch?

```diff
diff --git a/cmake/FindPython.cmake b/cmake/FindPython.cmake
index 5513ff7..ab0307b 100644
--- a/cmake/FindPython.cmake
+++ b/cmake/FindPython.cmake
@@ -47,6 +47,9 @@ FIND_LIBRARY(PYTHON_LIBRARY NAMES
     NO_SYSTEM_ENVIRONMENT_PATH
     )
 
+add_library(python UNKNOWN IMPORTED)
+set_property(TARGET python PROPERTY IMPORTED_LOCATION ${PYTHON_LIBRARY})
+
 execute_process(
        COMMAND ${PYTHON_BIN} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
        OUTPUT_VARIABLE PYTHON_INSTALL_PATH_tmp
@@ -119,7 +122,7 @@ macro(ADD_PYTHON_LIBRARY name)
     ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
     set_target_properties(${name} PROPERTIES PREFIX "")
     set_target_properties(${name} PROPERTIES OUTPUT_NAME "${name}${PYTHON_EXTENSION_SOABI}")
-    target_link_libraries(${name} ${PYTHON_LIBRARY})
+    target_link_libraries(${name} python)
     IF(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
         set_target_properties(${name} PROPERTIES SUFFIX ".pyd")
     ENDIF()
```

**Comment by woodscn** [comment]
Results in the error:

```
~/git-repos/symengine.py$ python setup.py install build --symengine-dir=~
~/anaconda3/lib/python3.4/site-packages/setuptools-18.4-py3.4.egg/setuptools/dist.py:285: UserWarning: Normalizing '0.1.0.dev' to '0.1.0.dev0'
running install
running build
SymEngine_DIR : ~/lib/cmake/symengine
CMake Error: Error in cmake code at
~/git-repos/symengine.py/cmake/FindPython.cmake:47:
Parse error.  Expected a command name, got unquoted argument with text "+add_library".
CMake Error at CMakeLists.txt:14 (find_package):
  find_package Error reading CMake code from
  "~/git-repos/symengine.py/cmake/FindPython.cmake".


-- Found CYTHON: cython
CMAKE_BUILD_TYPE : Release
CMAKE_CXX_FLAGS_RELEASE : -std=c++11 -Wall -Wextra -fPIC -O3 -march=native -ffast-math -funroll-loops -Wno-unused-parameter -D__extern_always_inline=inline
CMAKE_CXX_FLAGS_DEBUG : -std=c++11 -Wall -Wextra -fPIC -g -Wno-unused-parameter -ggdb
HAVE_SYMENGINE_MPFR : False
HAVE_SYMENGINE_MPC : False
Copying source of python wrappers into: ~/git-repos/symengine.py
CMake Error at symengine/lib/CMakeLists.txt:10 (add_python_library):
  Unknown CMake command "add_python_library".


-- Configuring incomplete, errors occurred!
See also "~/git-repos/symengine.py/CMakeFiles/CMakeOutput.log".
error: error calling cmake
```

**Comment by woodscn** [comment]
Nevermind, turns out I'd accidentally copied the "+" from your patch. This does not fix the original problem, however.

**Comment by certik** [comment]
Thanks @woodscn for the bug report. How is it possible that our tests pass on a Mac, e.g. here: https://travis-ci.org/symengine/symengine.py/jobs/90321358? We need to improve our testing to test for the bug that you found.

**Comment by woodscn** [comment]
The whole process ends up being a bit hackish; it's entirely possible that I'm messing something up on my end. I'm also working with an Anaconda installation, in my user directory, and I'm running python 3.4 rather than 2.7. Lots of possibilities there.

Here's my process, FWIW, running cmake version 3.3.2 and python 3.4.

git clone both symengine and symengine.py
git checkout specific commit in symegine
cmake -D<set install path to be ~, which has bin, lib, and include directories available> .
This throws errors, but running cmake again finishes cleanly. No idea why.
make install
cd to symengine.py 
python setup.py install build --symengine-dir=<~>
Again, cmake throws errors the first time, but the second time finishes. 
Testing results in the error: 
```~$ python -c "import symengine"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/woodscn/anaconda3/lib/python3.4/site-packages/symengine/__init__.py", line 1, in <module>
    from .lib.symengine_wrapper import (Symbol, Integer, sympify, SympifyError,
ImportError: dlopen(/home/woodscn/anaconda3/lib/python3.4/site-packages/symengine/lib/symengine_wrapper.cpython-34m.so, 2): Library not loaded: libpython3.4m.dylib
  Referenced from: /home/woodscn/anaconda3/lib/python3.4/site-packages/symengine/lib/symengine_wrapper.cpython-34m.so
  Reason: image not found
```

This can be fixed following the procedure I linked to, or by symlinking libpython, but those are just temporary workarounds, and will break things if/when you change conda environments.

**Comment by certik** [comment]
Can you post your cmake log where it throws the error? You can use gist.github.com to post it. It should not throw any errors and it should just work with your cmake and Python 3.4 versions.

**Comment by woodscn** [comment]
Sure thing. While I figure out how to do that, here's a sample piece of output.

```
CMake Error: Error in cmake code at
/home/woodscn/Downloads/cmake-3.3.2-Darwin-x86_64/CMake.app/Contents/share/cmake-3.3/Modules/Compiler/._Borland-DetermineCompiler.cmake:1:
Parse error.  Expected a command name, got unquoted argument with text "".
CMake Error at /home/woodscn/Downloads/cmake-3.3.2-Darwin-x86_64/CMake.app/Contents/share/cmake-3.3/Modules/CMakeCompilerIdDetection.cmake:16 (include):
  include could not find load file:

    /home/woodscn/Downloads/cmake-3.3.2-Darwin-x86_64/CMake.app/Contents/share/cmake-3.3/Modules/Compiler/._Borland-DetermineCompiler.cmake
Call Stack (most recent call first):
  /home/woodscn/Downloads/cmake-3.3.2-Darwin-x86_64/CMake.app/Contents/share/cmake-3.3/Modules/CMakeCompilerIdDetection.cmake:44 (_readFile)
  /home/woodscn/Downloads/cmake-3.3.2-Darwin-x86_64/CMake.app/Contents/share/cmake-3.3/Modules/CMakeDetermineCompilerId.cmake:108 (compiler_id_detection)
  /home/woodscn/Downloads/cmake-3.3.2-Darwin-x86_64/CMake.app/Contents/share/cmake-3.3/Modules/CMakeDetermineCompilerId.cmake:126 (CMAKE_DETERMINE_COMPILER_ID_WRITE)
  /home/woodscn/Downloads/cmake-3.3.2-Darwin-x86_64/CMake.app/Contents/share/cmake-3.3/Modules/CMakeDetermineCompilerId.cmake:39 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /home/woodscn/Downloads/cmake-3.3.2-Darwin-x86_64/CMake.app/Contents/share/cmake-3.3/Modules/CMakeDetermineCXXCompiler.cmake:104 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)
```

**Comment by woodscn** [comment]
gist here: https://gist.github.com/woodscn/386a66d2faf75dbbd41f

**Comment by isuruf** [comment]
CMake error seems to be a bug in CMake.

Can you post `~/git-repos/symengine.py/symengine/lib/CMakeFiles/symengine_wrapper.dir/link.txt` and `~/git-repos/symengine.py/symengine/lib/CMakeFiles/symengine_wrapper.dir/flags.make` ?

Also what does your environment variables CC and CXX point to?

**Comment by woodscn** [comment]
link.txt:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -std=c++11 -Wall -Wextra -fPIC -O3 -march=native -ffast-math -funroll-loops -Wno-unused-parameter -D__extern_always_inline=inline -bundle -Wl,-headerpad_max_install_names -flat_namespace -undefined suppress -o symengine_wrapper.cpython-34m.so CMakeFiles/symengine_wrapper.dir/symengine_wrapper.cpp.o /home/woodscn/anaconda3/lib/libpython3.4m.dylib /home/woodscn/lib/libsymengine.a /home/woodscn/lib/libteuchos.a /home/woodscn/lib/libgmpxx.dylib /home/woodscn/lib/libgmp.dylib 
```
flags.make:
```
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# compile CXX with /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CXX_FLAGS = -std=c++11 -Wall -Wextra -fPIC -O3 -march=native -ffast-math -funroll-loops -Wno-unused-parameter -D__extern_always_inline=inline -fPIC -I/home/woodscn/git-repos/symengine.py/symengine/lib -I/home/woodscn/lib/cmake/symengine/../../../include -I/home/woodscn/include -I/home/woodscn/anaconda3/include/python3.4m   

CXX_DEFINES = -Dsymengine_wrapper_EXPORTS

# Custom flags: symengine/lib/CMakeFiles/symengine_wrapper.dir/symengine_wrapper.cpp.o_FLAGS = -fno-strict-aliasing -Wno-unused-function -Wno-constant-logical-operand
```

CC and CXX aren't set to anything in particular. I think that means they're using the defaults:
```
cc --version
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by isuruf** [comment]
Thanks for the info. 
The following mail thread describes the problem, https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/fUpqjkK5jEI

We should either,
1. Provide conda build script in the repo itself.
2. Use rpath for symengine.py as we want the relative path between `symengine_wrapper.so` and `libpython3.4m.dylib` to be fixed.

Or both.

@certik, regarding the test issue, we didn't see this because although we used Miniconda for python, there must have been a system python that was linked to `symengine_wrapper.so` at runtime.

**Comment by certik** [comment]
I thought that we already used 2., since cmake uses rpath. We should start with 2., how do we fix it?

We should also finish https://github.com/conda/conda-recipes/pull/145, but that's a separate issue.

Ondrej

**Comment by isuruf** [comment]
CMake does use rpath, but only absolute rpaths I think. So we should use for example, $ORIGIN based (for Linux) rpath or @loader_path based (for OS X) for the linked python library.

**Comment by certik** [comment]
Doing relative rpath with cmake like that is tricky I think. It's better to be left to the package manager.

Why do absolute rpaths not work?

**Comment by woodscn** [comment]
My understanding is that it's ambiguous to link to a specific Python, since conda environments may change which one is being called regularly. However, linking directly with whichever Python was used to build the package would be okay. That's what ```pip``` does, after all, and you just have to reinstall the package anytime you switch to a new environment.

**Comment by certik** [comment]
That's exactly right. I thought we already link to the Python version with absolute paths. Either way, that should work and that's what we need to support.

In order to get better integration with Conda, one needs to finnish the https://github.com/conda/conda-recipes/pull/145 PR, which is a separate/orthogonal issue.
