### ISSUE TITLE
Lambdify with Piecewise

### ISSUE THREAD

**Issue by stephweissm** [symengine/symengine.py#234]
First off: big thanks for this package, truly amazing effort!

Short qustion: is `Piecewise` supposed to work with `Lambdify`?:

```
$ conda install -c symengine/label/dev python-symengine
$ python
>>> from symengine import Symbol, Lambdify
>>> from symengine.lib.symengine_wrapper import Piecewise
>>> x = Symbol('x')
>>> p = Piecewise((-x, x<0), (x*x*x, True))
>>> p
Piecewise((-x, x < 0), (x**3, True))
>>> f = Lambdify([x], [p])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "symengine_wrapper.pyx", line 4793, in symengine.lib.symengine_wrapper.Lambdify
  File "symengine_wrapper.pyx", line 4481, in symengine.lib.symengine_wrapper._Lambdify.__init__
  File "symengine_wrapper.pyx", line 4671, in symengine.lib.symengine_wrapper.LambdaDouble._init
RuntimeError: Not Implemented
```

**Comment by isuruf** [comment]
It is supposed to, but it's not implemented yet. (Because nobody wanted this feature yet.)
It's simple to add this though. You'll need to add a method somewhere over [here](https://github.com/symengine/symengine/blob/master/symengine/lambda_double.h#L393)
