### ISSUE TITLE
ComplexDouble constructor only accepts one argument

### ISSUE THREAD

**Issue by rikardn** [symengine/symengine.py#328]
The constructor for `ComplexDouble` only accepts the real part as argument:

```python
import symengine

symengine.ComplexDouble(1, 1)
```

gives 

```
Traceback (most recent call last):

  File "<ipython-input-8-c103ac94069e>", line 1, in <module>
    symengine.ComplexDouble(1, 1)

  File "symengine_wrapper.pyx", line 1848, in symengine.lib.symengine_wrapper.ComplexDouble.__cinit__

TypeError: __cinit__() takes at most 1 positional argument (2 given)
```

but

```symengine
import symengine
symengine.ComplexDouble(1)
```

gives

```
1.0 + 0.0*I
```

**Comment by rikardn** [comment]
Sorry, I misunderstood the interface:

```python
import symengine
symengine.ComplexDouble(1+1j)
```

works perfectly fine
