### ISSUE TITLE
logic operations don't support symbols

### ISSUE THREAD

**Issue by ahmedantaar** [symengine/symengine.py#334]
The logic operations don't support symbols like arithmetic operations, I tried it in sympy but it was super slow but in symengine it gives me errors. I don't know if it's implemented and I don't know or what.

Thanks in advance.

**Comment by rikardn** [comment]
Could you please provide a short example program that doesn't work as expected?

**Comment by ertsiger** [comment]
Hi, I've just started experimenting a bit with `symengine` given that `sympy` is a bit slow for some operations, but I have found a case similar to what @ahmedantaar is describing. For example, the following code snippet does not work:
```
from symengine import sympify
formula = sympify("a & b")
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

I have also tried to do the following:
```
from symengine import symbols
a, b = symbols("a b")
formula = a & b
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: unsupported operand type(s) for &: 'symengine.lib.symengine_wrapper.Symbol' and 'symengine.lib.symengine_wrapper.Symbol'
```

Given that the operator seems undefined I went for using `And` instead over these two symbols, but it does not seem to work either:
```
from symengine.lib.symengine_wrapper import And
from symengine import symbols
a, b = symbols("a b")
formula = And(a, b)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "symengine_wrapper.pyx", line 1401, in symengine.lib.symengine_wrapper.And.__new__
  File "symengine_wrapper.pyx", line 3991, in symengine.lib.symengine_wrapper.logical_and
TypeError: Cannot convert symengine.lib.symengine_wrapper.Symbol to symengine.lib.symengine_wrapper.Boolean
```

I have also taken a look at the test cases but none of them are using symbols, so I'm not sure if I'm doing something wrong or the features I intend to use are unsupported as of now.

Thanks.

**Comment by rikardn** [comment]
Unfortunately symengine does not yet support symbols taking on boolean values.
