### ISSUE TITLE
Symengine importing problem in MacOS

### ISSUE THREAD

**Issue by imaneekjana** [symengine/symengine.py#445]
I am having the following problem while importing symengine in my MacOS.

>>> import symengine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aneekphys/symengine/build/symengine.py/symengine/__init__.py", line 12, in <module>
    import symengine.lib.symengine_wrapper as wrapper
ImportError: dlopen(/Users/aneekphys/symengine/build/symengine.py/symengine/lib/symengine_wrapper.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace (__ZN9SymEngine10ComplementC1ERKNS_3RCPIKNS_3SetEEES6_)

cannot find a way to resolve it.

**Comment by isuruf** [comment]
Have you tried the pip wheel? `pip install symengine`?
