### ISSUE TITLE
Seg Fault Running Given Lambdify Benchmark

### ISSUE THREAD

**Issue by jyting** [symengine/symengine.py#89]
Hi,

Upon successfully setting up symengine, running the Lambidfy.py file unfortunately immediately ended in a segfault at the lambdification line. Running the program with sys.settrace set to the 'line' function and running python inside gdb, I get the following error trace:

> (gdb) run Lambdify.py 
> Starting program: /usr/bin/python Lambdify.py
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/usr/lib/libthread_db.so.1".
> [New Thread 0x7ffff4aa4700 (LWP 31641)]
> [New Thread 0x7ffff42a3700 (LWP 31642)]
> [New Thread 0x7fffefaa2700 (LWP 31643)]
> Traceback (most recent call last):
>   File "Lambdify.py", line 11, in <module>
>     x = sp.symarray('x', 14)
>   File "/usr/lib/python3.5/site-packages/sympy/matrices/dense.py", line 998, in symarray
>     @doctest_depends_on(modules=('numpy',))
> TypeError: 'str' object is not callable
> [Thread 0x7fffefaa2700 (LWP 31643) exited]
> [Thread 0x7ffff42a3700 (LWP 31642) exited]
> [Thread 0x7ffff4aa4700 (LWP 31641) exited]
> [Inferior 1 (process 31637) exited with code 01]

**Comment by isuruf** [comment]
Hi,
Thanks for trying out symengine and reporting errors.

This seems to be an error in sympy.
Does,
```
import sympy as sp
x = sp.symarray('x', 14)
``` 
work?

Btw, benchmarks like `expand2.py` needs to be run in a session with `USE_SYMENGINE` env variable set to 1. Otherwise it will use sympy.

Can you comment on #88 about how you fixed the problem you mentioned? It'll be useful for other users.

**Comment by jyting** [comment]
@isuruf Yep, I'll go ahead and mention what I did to fix the issue!

The code snippet you posted above works - tested just then, I can similarly use such symarrays to divide into matrices/multi-dimensional data, lambdify those and evaluate them, etc.

Does this change what you suspect may be wrong? If it is indeed a sympy bug I can post the same information as a bug under the sympy project.

**Comment by certik** [comment]
Thanks @jyting for trying it out and getting everything working. How big speedups did you get on your problem?

**Comment by jyting** [comment]
@certik I wasn't able to benchmark on my problem unfortunately, as I wasn't able to get past the seg fault from above for the problems I was trying to test out :(

**Comment by certik** [comment]
@jyting Can you send us your script? Let's debug the problem. I don't see a segfault, just a Python exception.
